### ISSUE TITLE
General mobile friendliness improvements

### ISSUE THREAD

**Issue by KevinNovak** [mzrimsek/track-my-playtime#49]
The mobile experience could use possible improvements: avoiding text overlapping, smaller font sizes, maybe putting the sidebar in a toggle-able menu for more room. 

![](https://i.imgur.com/kJbX0Z5.png)

**Comment by mzrimsek** [comment]
I have a card for this added here ( #23 ). I've been working on making some incremental changes as I do work here and there, though styling is definitely not my forte.

I still think I plan to make a native app, at least for Android at some point, but I agree it should look better on mobile.
